import { isBusinessManager } from "../utils/roles.js";
import database from "../config/db.js";
import { processImage } from "./imageProcessor.service.js";
import { createSignedStorageUrls, deleteStorageObject, uploadStorageObject } from "./storage.service.js";

const BUCKET = "photos_personne";
const OPEN = "EN_CONSULTATION";
const EDITABLE = "VISIBLE";
function err(message, code) { const error = new Error(message); error.code = code; return error; }
function open(row) { return row.statut_code === OPEN && row.date_fin_consultation && new Date(row.date_serveur) < new Date(row.date_fin_consultation); }
async function lockSoso(id) { const r = await database.query(`SELECT s.id, s.date_fin_consultation, statut.code AS statut_code, now() AS date_serveur FROM soso_kevitra s JOIN statut_soso_kevitra statut ON statut.id=s.id_statut_soso_kevitra WHERE s.id=$1 FOR UPDATE OF s`,[id]); return r.rows[0] ?? null; }
async function activeCategory(code) { if(typeof code!=="string"||!code.trim()) throw err("La catégorie est obligatoire","CONTRIBUTION_INVALID"); const r=await database.query("SELECT id, code FROM soso_kevitra_categorie_contribution WHERE code=$1 AND actif=true",[code.trim().toUpperCase()]); if(!r.rows[0]) throw err("Catégorie invalide ou inactive","CONTRIBUTION_CATEGORY_INVALID"); return r.rows[0]; }
function text(v,name,max=200) { if(typeof v!=="string"||!v.trim()||v.trim().length>max) throw err(`Le champ ${name} est obligatoire`,"CONTRIBUTION_INVALID"); return v.trim(); }
async function contribution(id,idContribution,{lock=false}={}) { const r=await database.query(`SELECT c.*, s.id AS soso_id, s.date_fin_consultation, statut.code AS statut_code, now() AS date_serveur FROM soso_kevitra_contribution c JOIN soso_kevitra s ON s.id=c.id_soso_kevitra JOIN statut_soso_kevitra statut ON statut.id=s.id_statut_soso_kevitra WHERE c.id=$1 AND c.id_soso_kevitra=$2 ${lock?"FOR UPDATE OF c,s":""}`,[idContribution,id]); return r.rows[0]??null; }
function assertOwnerEditable(c,personne) { if(c.id_auteur!==personne) throw err("Accès interdit","CONTRIBUTION_FORBIDDEN"); if(!open(c)) throw err("La consultation est fermée","CONSULTATION_CLOSED"); if(c.etat!==EDITABLE) throw err("Cette contribution n'est plus modifiable","CONTRIBUTION_STATE_INVALID"); }
async function photos(contributionIds) { if(!contributionIds.length)return new Map(); const r=await database.query(`SELECT * FROM soso_kevitra_contribution_photo WHERE id_contribution = ANY($1::uuid[]) ORDER BY ordre ASC`,[contributionIds]); const urls=await createSignedStorageUrls(BUCKET,r.rows.map(x=>x.chemin_photo)); const map=new Map(); for(const p of r.rows){const a=map.get(p.id_contribution)??[]; a.push({...p,url:urls.get(p.chemin_photo),url_photo:urls.get(p.chemin_photo)});map.set(p.id_contribution,a);} return map; }
export async function listContributions(id,auth,lang="fr") {
  const r=await database.query(`SELECT c.*, cat.code, tr.libelle, p.id auteur_id,p.nom,p.prenom,p.nom_usage, s.date_fin_consultation, statut_soso.code AS statut_code, now() AS date_serveur FROM soso_kevitra_contribution c JOIN soso_kevitra s ON s.id=c.id_soso_kevitra JOIN statut_soso_kevitra statut_soso ON statut_soso.id=s.id_statut_soso_kevitra JOIN soso_kevitra_categorie_contribution cat ON cat.id=c.id_categorie LEFT JOIN langue l ON lower(l.code)=$2 LEFT JOIN soso_kevitra_categorie_contribution_traduction tr ON tr.id_categorie=cat.id AND tr.id_langue=l.id JOIN personne p ON p.id=c.id_auteur WHERE c.id_soso_kevitra=$1 ORDER BY c.date_creation ASC,c.id ASC`,[id,lang]);
  const contributionIds=r.rows.map(x=>x.id);
  const pm=await photos(contributionIds);
  const viewer=auth?.personne?.id;
  const admin=isBusinessManager(auth?.compte?.role);
  const moderation=admin || r.rows.some((item) => item.id_auteur === viewer) ? await database.query(`SELECT m.id,m.id_contribution,m.action,m.raison,m.date_action,p.id personne_id,p.nom,p.prenom,p.nom_usage FROM soso_kevitra_moderation_contribution m JOIN personne p ON p.id=m.id_admin WHERE m.id_contribution=ANY($1::uuid[]) ORDER BY m.date_action ASC,m.id ASC`,[contributionIds]) : {rows:[]};
  const histories=new Map();
  for(const item of moderation.rows){const list=histories.get(item.id_contribution)??[];list.push({action:item.action,raison:item.raison,date_action:item.date_action,personne_action:{id:item.personne_id,nom:item.nom,prenom:item.prenom,nom_usage:item.nom_usage}});histories.set(item.id_contribution,list);}
  return r.rows.filter(x=>x.etat==="VISIBLE"||x.id_auteur===viewer||admin).map(x=>{const privileged=admin||x.id_auteur===viewer;const consultationOuverte=open(x);return {id:x.id,categorie:{id:x.id_categorie,code:x.code,libelle:x.libelle},titre:x.etat==="VISIBLE"||privileged?x.titre:null,description:x.etat==="VISIBLE"||privileged?x.description:null,etat:x.etat,date_creation:x.date_creation,date_modification:x.date_modification,date_retrait:x.date_retrait,auteur:{id:x.auteur_id,nom:x.nom,prenom:x.prenom,nom_usage:x.nom_usage},photos:pm.get(x.id)??[],...(privileged?{moderation_historique:histories.get(x.id)??[]}:{}),peut_modifier:x.id_auteur===viewer&&x.etat===EDITABLE&&consultationOuverte,peut_retirer:x.id_auteur===viewer&&x.etat===EDITABLE&&consultationOuverte};});
}
export async function createContribution(id,body,auth,lang){const person=auth?.personne?.id;if(!person)throw err("Authentification requise","AUTH_REQUIRED"); const cat=await activeCategory(body?.categorie);const titre=text(body?.titre,"titre");const description=text(body?.description,"description",100000);const created=await database.transaction(async()=>{const s=await lockSoso(id);if(!s)return null;if(!open(s))throw err("La consultation est fermée","CONSULTATION_CLOSED");const r=await database.query(`INSERT INTO soso_kevitra_contribution(id_soso_kevitra,id_auteur,id_categorie,titre,description) VALUES($1,$2,$3,$4,$5) RETURNING id`,[id,person,cat.id,titre,description]);return r.rows[0].id;}); if(!created)return null;return (await listContributions(id,auth,lang)).find(x=>x.id===created);}
export async function updateContribution(id,cid,body,auth,lang){const person=auth?.personne?.id;const cat=await activeCategory(body?.categorie);const titre=text(body?.titre,"titre");const description=text(body?.description,"description",100000);return database.transaction(async()=>{const c=await contribution(id,cid,{lock:true});if(!c)return null;assertOwnerEditable(c,person);await database.query(`UPDATE soso_kevitra_contribution SET id_categorie=$1,titre=$2,description=$3,date_modification=now() WHERE id=$4`,[cat.id,titre,description,cid]);return true;});}export async function withdrawContribution(id,cid,auth){const person=auth?.personne?.id;return database.transaction(async()=>{const c=await contribution(id,cid,{lock:true});if(!c)return null;assertOwnerEditable(c,person);await database.query("UPDATE soso_kevitra_contribution SET etat='RETIRE',date_retrait=now(),date_modification=now() WHERE id=$1",[cid]);return true;});}
async function moderate(id,cid,body,auth,restore=false){const admin=auth?.personne?.id;if(!admin)throw err("Authentification requise","AUTH_REQUIRED"); if(!isBusinessManager(auth?.compte?.role))throw err("Accès administrateur requis","CONTRIBUTION_FORBIDDEN");const raison=text(body?.raison,"raison",100000);return database.transaction(async()=>{const c=await contribution(id,cid,{lock:true});if(!c)return null;const expected=restore?"MASQUE":"VISIBLE";if(c.etat!==expected)throw err("Transition de modération impossible","CONTRIBUTION_STATE_INVALID");await database.query("UPDATE soso_kevitra_contribution SET etat=$1,date_modification=now() WHERE id=$2",[restore?"VISIBLE":"MASQUE",cid]);await database.query("INSERT INTO soso_kevitra_moderation_contribution(id_contribution,action,raison,id_admin) VALUES($1,$2,$3,$4)",[cid,restore?"RESTAURER":"MASQUER",raison,admin]);return true;});}
export const masquerContribution=(id,cid,body,auth)=>moderate(id,cid,body,auth,false); export const restaurerContribution=(id,cid,body,auth)=>moderate(id,cid,body,auth,true);
const PHOTO_LIMIT=5;
async function editableContributionPhoto(id,cid,auth){const c=await contribution(id,cid,{lock:true});if(!c)return null;assertOwnerEditable(c,auth?.personne?.id);return c;}
async function contributionPhotoRows(cid,lock=false){const r=await database.query(`SELECT id,id_contribution,chemin_photo,ordre,date_creation FROM soso_kevitra_contribution_photo WHERE id_contribution=$1 ORDER BY ordre ASC ${lock?"FOR UPDATE":""}`,[cid]);return r.rows;}
async function reindexContributionPhotos(cid,ids){if(!ids.length)return;const r=await database.query("SELECT COALESCE(MAX(ordre),0) max FROM soso_kevitra_contribution_photo WHERE id_contribution=$1",[cid]);const offset=Number(r.rows[0].max)+ids.length+1;await database.query("UPDATE soso_kevitra_contribution_photo SET ordre=ordre+$1 WHERE id_contribution=$2",[offset,cid]);for(const [i,pid] of ids.entries())await database.query("UPDATE soso_kevitra_contribution_photo SET ordre=$1 WHERE id=$2 AND id_contribution=$3",[i+1,pid,cid]);}
export async function uploadContributionPhotos(id,cid,files,auth){if(!Array.isArray(files)||!files.length)throw err("Au moins une photo est obligatoire","PHOTO_REQUIRED");if(files.length>PHOTO_LIMIT)throw err("Une contribution ne peut pas contenir plus de 5 photos","CONTRIBUTION_PHOTO_LIMIT");const images=await Promise.all(files.map(processImage));const uploaded=[];let rows;try{rows=await database.transaction(async()=>{const c=await editableContributionPhoto(id,cid,auth);if(!c)return null;const existing=await contributionPhotoRows(cid,true);if(existing.length+images.length>PHOTO_LIMIT)throw err("Une contribution ne peut pas contenir plus de 5 photos","CONTRIBUTION_PHOTO_LIMIT");const out=[];for(const [i,image] of images.entries()){const path=`soso-kevitra/contributions/${cid}/${crypto.randomUUID()}.webp`;await uploadStorageObject(BUCKET,path,image,"image/webp");uploaded.push(path);const r=await database.query("INSERT INTO soso_kevitra_contribution_photo(id_contribution,chemin_photo,ordre) VALUES($1,$2,$3) RETURNING id,id_contribution,chemin_photo,ordre,date_creation",[cid,path,existing.length+i+1]);out.push(r.rows[0]);}return out;});}catch(error){await Promise.all(uploaded.map(p=>deleteStorageObject(BUCKET,p,{allowNotFound:true}).catch(()=>{})));throw error;}if(!rows)return null;const urls=await createSignedStorageUrls(BUCKET,rows.map(x=>x.chemin_photo));return rows.map(x=>({...x,url:urls.get(x.chemin_photo),url_photo:urls.get(x.chemin_photo)}));}
export async function deleteContributionPhoto(id,cid,pid,auth){return database.transaction(async()=>{const c=await editableContributionPhoto(id,cid,auth);if(!c)return null;const r=await database.query("SELECT id,id_contribution,chemin_photo,ordre,date_creation FROM soso_kevitra_contribution_photo WHERE id=$1 AND id_contribution=$2 FOR UPDATE",[pid,cid]);const photo=r.rows[0];if(!photo)return undefined;await deleteStorageObject(BUCKET,photo.chemin_photo,{allowNotFound:true});await database.query("DELETE FROM soso_kevitra_contribution_photo WHERE id=$1 AND id_contribution=$2",[pid,cid]);const rest=await contributionPhotoRows(cid,true);await reindexContributionPhotos(cid,rest.map(x=>x.id));return photo;});}
export async function reorderContributionPhotos(id,cid,ids,auth){if(!Array.isArray(ids)||new Set(ids).size!==ids.length)throw err("La liste des photos est invalide","CONTRIBUTION_PHOTO_INVALID");return database.transaction(async()=>{const c=await editableContributionPhoto(id,cid,auth);if(!c)return null;const existing=await contributionPhotoRows(cid,true);const known=new Set(existing.map(x=>x.id));if(ids.length!==existing.length||ids.some(x=>typeof x!=="string"||!known.has(x)))throw err("La liste des photos doit être complète","CONTRIBUTION_PHOTO_INVALID");await reindexContributionPhotos(cid,ids);return contributionPhotoRows(cid);});}