-- PITIKORANA
-- Migration 18 : géographie Madagascar (24 régions) à partir de all-commune.json
-- IMPORTANT : aucun changement de schéma. Le district n'est pas stocké.
-- En cas d'homonyme dans une même région, le district est ajouté au libellé : Commune (District).
-- Référentiel source local : 1 579 communes. Cette migration conserve les 1 579 entrées.
-- Découpage courant appliqué : Ambatosoa + séparation Vatovavy / Fitovinany.
-- ATTENTION : le total légal national actuel est 1 695 communes ; le fichier source local n'en contient que 1 579.
-- Cette migration est donc sûre pour le référentiel fourni, mais ne prétend pas compléter les 116 communes absentes de ce fichier.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pays WHERE nom = 'Madagascar') THEN
    RAISE EXCEPTION 'Madagascar absent de pays';
  END IF;
  IF EXISTS (
    SELECT 1 FROM personne p JOIN ville v ON v.id=p.id_ville JOIN region r ON r.id=v.id_region JOIN pays py ON py.id=r.id_pays WHERE py.nom='Madagascar'
  ) THEN
    RAISE EXCEPTION 'Des personnes utilisent déjà des villes Madagascar : migration annulée';
  END IF;
END $$;

-- Nettoyage Madagascar uniquement. Les autres pays ne sont pas touchés.
DELETE FROM ville WHERE id_region IN (SELECT r.id FROM region r JOIN pays p ON p.id=r.id_pays WHERE p.nom='Madagascar');
DELETE FROM region WHERE id_pays=(SELECT id FROM pays WHERE nom='Madagascar');

-- 24 régions
INSERT INTO region (nom,id_pays)
SELECT x.nom,p.id FROM (VALUES
  ('Alaotra Mangoro'),
  ('Ambatosoa'),
  ('Amoron I Mania'),
  ('Analamanga'),
  ('Analanjirofo'),
  ('Androy'),
  ('Anosy'),
  ('Atsimo Andrefana'),
  ('Atsimo Atsinanana'),
  ('Atsinanana'),
  ('Betsiboka'),
  ('Boeny'),
  ('Bongolava'),
  ('Diana'),
  ('Fitovinany'),
  ('Haute Matsiatra'),
  ('Ihorombe'),
  ('Itasy'),
  ('Melaky'),
  ('Menabe'),
  ('Sava'),
  ('Sofia'),
  ('Vakinankaratra'),
  ('Vatovavy')
) AS x(nom) CROSS JOIN pays p WHERE p.nom='Madagascar'
ON CONFLICT (nom,id_pays) DO NOTHING;

-- Communes (ville) par lots logiques via VALUES
INSERT INTO ville (nom,id_region)
SELECT x.nom,r.id
FROM (VALUES
  ('Analamanga', '1er Arrondissement'),
  ('Analamanga', '2e Arrondissement'),
  ('Analamanga', '3e Arrondissement'),
  ('Analamanga', '4e Arrondissement'),
  ('Analamanga', '5e Arrondissement'),
  ('Analamanga', '6e Arrondissement'),
  ('Analamanga', 'Alasora'),
  ('Analamanga', 'Ankadikely Ilafy'),
  ('Analamanga', 'Ambohimanambola'),
  ('Analamanga', 'Sabotsy Namehana'),
  ('Analamanga', 'Ambohimangakely'),
  ('Analamanga', 'Manandriana'),
  ('Analamanga', 'Ambohimalaza Miray'),
  ('Analamanga', 'Fiaferana'),
  ('Analamanga', 'Ambohimanga Rova'),
  ('Analamanga', 'Viliahazo'),
  ('Analamanga', 'Talata Volonondry'),
  ('Analamanga', 'Anjeva Gara'),
  ('Analamanga', 'Masindray'),
  ('Analamanga', 'Ankadinandriana'),
  ('Analamanga', 'Ambohidratrimo'),
  ('Analamanga', 'Anosiala'),
  ('Analamanga', 'Talatamaty'),
  ('Analamanga', 'Antehiroka'),
  ('Analamanga', 'Iarinarivo'),
  ('Analamanga', 'Ivato Firaisana'),
  ('Analamanga', 'Ivato Aeroport'),
  ('Analamanga', 'Ambohitrimanjaka'),
  ('Analamanga', 'Mahitsy'),
  ('Analamanga', 'Merimandroso'),
  ('Analamanga', 'Ambatolampy'),
  ('Analamanga', 'Ampangabe'),
  ('Analamanga', 'Ampanotokana'),
  ('Analamanga', 'Mananjara'),
  ('Analamanga', 'Manjakavaradrano'),
  ('Analamanga', 'Antsahafilo'),
  ('Analamanga', 'Ambohimanjaka'),
  ('Analamanga', 'Fiadanana (Ambohidratrimo)'),
  ('Analamanga', 'Mahabo'),
  ('Analamanga', 'Mahereza'),
  ('Analamanga', 'Antanetibe (Ambohidratrimo)'),
  ('Analamanga', 'Ambohipihaonana'),
  ('Analamanga', 'Ambato'),
  ('Analamanga', 'Anjanadoria'),
  ('Analamanga', 'Avaratsena'),
  ('Analamanga', 'Ankazobe'),
  ('Analamanga', 'Talata Angavo'),
  ('Analamanga', 'Ambohitromby'),
  ('Analamanga', 'Antotohazo (Ankazobe)'),
  ('Analamanga', 'Marondry'),
  ('Analamanga', 'Fihaonana'),
  ('Analamanga', 'Mahavelona'),
  ('Analamanga', 'Fiadanana (Ankazobe)'),
  ('Analamanga', 'Tsaramasoandro'),
  ('Analamanga', 'Ambolotarakely'),
  ('Analamanga', 'Antakavana'),
  ('Analamanga', 'Kiangara'),
  ('Analamanga', 'Miantso'),
  ('Analamanga', 'Manjakandriana'),
  ('Analamanga', 'Ambatolaona'),
  ('Analamanga', 'Sambaina'),
  ('Analamanga', 'Ambohibary'),
  ('Analamanga', 'Ambatomanga'),
  ('Analamanga', 'Alarobia'),
  ('Analamanga', 'Mantasoa'),
  ('Analamanga', 'Ranovao'),
  ('Analamanga', 'Miadanandriana'),
  ('Analamanga', 'Nandihizana'),
  ('Analamanga', 'Anjepy'),
  ('Analamanga', 'Ambanitsena'),
  ('Analamanga', 'Ambohitrandriamanitra'),
  ('Analamanga', 'Ambatomena'),
  ('Analamanga', 'Ambohibao Sud'),
  ('Analamanga', 'Ambohitseheno'),
  ('Analamanga', 'Antsahalalina'),
  ('Analamanga', 'Sabotsy Ambohitromby'),
  ('Analamanga', 'Andohariana'),
  ('Analamanga', 'Mandrosoa'),
  ('Analamanga', 'Ambatofahavalo'),
  ('Vakinankaratra', 'Antsenakely Andraikiba'),
  ('Vakinankaratra', 'Ampatana Mandriankeniheny'),
  ('Vakinankaratra', 'Ampitatafika'),
  ('Vakinankaratra', 'Ambatomiady'),
  ('Vakinankaratra', 'Andranofito'),
  ('Haute Matsiatra', 'Fenoarivo'),
  ('Haute Matsiatra', 'Ambohimahasoa'),
  ('Haute Matsiatra', 'Ampitana'),
  ('Amoron I Mania', 'Ambohipo'),
  ('Amoron I Mania', 'Anjoman''ankona'),
  ('Amoron I Mania', 'Vinany Andakatanikely'),
  ('Fitovinany', 'Ankarimbelo'),
  ('Fitovinany', 'Antodinga'),
  ('Fitovinany', 'Kalafotsy'),
  ('Atsimo Atsinanana', 'Antondabe'),
  ('Atsimo Atsinanana', 'Marovitsika Sud'),
  ('Atsimo Atsinanana', 'Antaninarenina'),
  ('Analamanga', 'Ambohitrony'),
  ('Analamanga', 'Merikanjaka'),
  ('Analamanga', 'Anjoma Betoho'),
  ('Analamanga', 'Ankazondandy'),
  ('Analamanga', 'Soavinandriana'),
  ('Analamanga', 'Ambohitrolomahitsy'),
  ('Analamanga', 'Ampaneva'),
  ('Analamanga', 'Sadabe'),
  ('Analamanga', 'Anjozorobe'),
  ('Analamanga', 'Mangamila'),
  ('Analamanga', 'Ambongamarina'),
  ('Analamanga', 'Tsarasaotra'),
  ('Analamanga', 'Ambohimanarina Marovazaha'),
  ('Analamanga', 'Betatao'),
  ('Analamanga', 'Alakamisy'),
  ('Analamanga', 'Analaroa'),
  ('Analamanga', 'Antanetibe (Anjozorobe)'),
  ('Analamanga', 'Belanitra'),
  ('Analamanga', 'Ambatomanoina'),
  ('Analamanga', 'Amparatanjona'),
  ('Analamanga', 'Amboasary Nord'),
  ('Analamanga', 'Androvakely'),
  ('Analamanga', 'Ambohibary Vohilena'),
  ('Analamanga', 'Ambohimirary'),
  ('Analamanga', 'Marotsipoy'),
  ('Analamanga', 'Beronono'),
  ('Analamanga', 'Andramasina'),
  ('Analamanga', 'Alatsinainy Bakaro'),
  ('Analamanga', 'Antotohazo (Andramasina)'),
  ('Analamanga', 'Ambohimiadana'),
  ('Analamanga', 'Tankafatra'),
  ('Analamanga', 'Alarobia Vatosola'),
  ('Analamanga', 'Fitsinjovana Bakaro'),
  ('Analamanga', 'Sabotsy Manjakavahoaka'),
  ('Analamanga', 'Anosibe Trimoloharano'),
  ('Analamanga', 'Ampitatafika'),
  ('Analamanga', 'Anosizato Andrefana'),
  ('Analamanga', 'Andranonahoatra'),
  ('Analamanga', 'Ambohidrapeto'),
  ('Analamanga', 'Bemasoandro'),
  ('Analamanga', 'Fiombonana'),
  ('Analamanga', 'Itaosy'),
  ('Analamanga', 'Ambavahaditokana'),
  ('Analamanga', 'Tanjombato'),
  ('Analamanga', 'Andoharanofotsy'),
  ('Analamanga', 'Ankaraobato'),
  ('Analamanga', 'Soalandy'),
  ('Analamanga', 'Antanetikely'),
  ('Analamanga', 'Alatsinainy Ambazaha'),
  ('Analamanga', 'Ampanefy'),
  ('Analamanga', 'Ankadimanga'),
  ('Analamanga', 'Fenoarivo'),
  ('Analamanga', 'Alakamisy Fenoarivo'),
  ('Analamanga', 'Soavina'),
  ('Analamanga', 'Ambohijanaka'),
  ('Analamanga', 'Ampahitrosy'),
  ('Analamanga', 'Bongatsara'),
  ('Analamanga', 'Androhibe'),
  ('Analamanga', 'Tsiafahy'),
  ('Analamanga', 'Ambalavao'),
  ('Vakinankaratra', 'Soamalaza Mahatsinjo'),
  ('Vakinankaratra', 'Antsirabe Afovoany Atsinanana'),
  ('Vakinankaratra', 'Manodidina Ny Gara Ambilombe'),
  ('Vakinankaratra', 'Mahazoarivo Avarabohitra'),
  ('Vakinankaratra', 'Betafo'),
  ('Vakinankaratra', 'Andranomafana'),
  ('Vakinankaratra', 'Mandritsara'),
  ('Vakinankaratra', 'Alakamisy Anativato'),
  ('Vakinankaratra', 'Antsoso'),
  ('Vakinankaratra', 'Tritriva'),
  ('Vakinankaratra', 'Soavina'),
  ('Vakinankaratra', 'Manohisoa'),
  ('Vakinankaratra', 'Ambatonikolahy'),
  ('Vakinankaratra', 'Antohobe'),
  ('Vakinankaratra', 'Mahaiza'),
  ('Vakinankaratra', 'Anosiarivo Manapa'),
  ('Vakinankaratra', 'Alakamisy Marososona'),
  ('Vakinankaratra', 'Ambohimanambola'),
  ('Vakinankaratra', 'Ambohimasina'),
  ('Vakinankaratra', 'Inanantonana'),
  ('Vakinankaratra', 'Alarobia Bemaha'),
  ('Vakinankaratra', 'Andrembesoa'),
  ('Vakinankaratra', 'Ambatolampy'),
  ('Vakinankaratra', 'Morarano'),
  ('Vakinankaratra', 'Ambohipihaonana'),
  ('Vakinankaratra', 'Manjakatompo'),
  ('Vakinankaratra', 'Ambatondrakalavao'),
  ('Vakinankaratra', 'Andriambilany'),
  ('Vakinankaratra', 'Belambo Firaisana'),
  ('Vakinankaratra', 'Andravola Vohipeno'),
  ('Vakinankaratra', 'Tsiafajavona Ankaratra'),
  ('Vakinankaratra', 'Ambodifarihy Fenomanana'),
  ('Vakinankaratra', 'Sabotsy Namatoana'),
  ('Vakinankaratra', 'Antanimasaka'),
  ('Vakinankaratra', 'Behenjy'),
  ('Vakinankaratra', 'Antsampandrano (Ambatolampy)'),
  ('Vakinankaratra', 'Antanamalaza'),
  ('Vakinankaratra', 'Antakasina'),
  ('Vakinankaratra', 'Tsinjoarivo'),
  ('Vakinankaratra', 'Andranovelona'),
  ('Vakinankaratra', 'Antanifotsy'),
  ('Vakinankaratra', 'Ambatolahy'),
  ('Vakinankaratra', 'Ambohimandroso'),
  ('Vakinankaratra', 'Ambatotsipihina'),
  ('Vakinankaratra', 'Ambohitompoina'),
  ('Vakinankaratra', 'Belanitra'),
  ('Vakinankaratra', 'Antsahalava'),
  ('Vakinankaratra', 'Ambodiriana'),
  ('Vakinankaratra', 'Antsampandrano (Antanifotsy)'),
  ('Vakinankaratra', 'Faratsiho'),
  ('Vakinankaratra', 'Antsampanimahazo'),
  ('Vakinankaratra', 'Faravohitra'),
  ('Vakinankaratra', 'Ramainandro'),
  ('Vakinankaratra', 'Andranomiady'),
  ('Vakinankaratra', 'Vinaninony Atsimo'),
  ('Vakinankaratra', 'Ambohiborona'),
  ('Vakinankaratra', 'Miandrarivo'),
  ('Vakinankaratra', 'Valabetokana'),
  ('Vakinankaratra', 'Ambano'),
  ('Vakinankaratra', 'Belazao'),
  ('Vakinankaratra', 'Alakamisy'),
  ('Vakinankaratra', 'Antanimandry'),
  ('Vakinankaratra', 'Vinaninkarena'),
  ('Vakinankaratra', 'Andranomanelatra'),
  ('Vakinankaratra', 'Ambohidranandriana'),
  ('Vakinankaratra', 'Ambohimiarivo'),
  ('Vakinankaratra', 'Ambohitsimanova'),
  ('Vakinankaratra', 'Mangarano'),
  ('Vakinankaratra', 'Manandona'),
  ('Vakinankaratra', 'Antsoatany'),
  ('Vakinankaratra', 'Alatsinainy Ibity'),
  ('Vakinankaratra', 'Sahanivotry Manandona'),
  ('Vakinankaratra', 'Soanindrariny'),
  ('Vakinankaratra', 'Ambatomena'),
  ('Vakinankaratra', 'Ambohibary'),
  ('Vakinankaratra', 'Mandrosohasina'),
  ('Vakinankaratra', 'Tsarahonenana Sahanivotry'),
  ('Vakinankaratra', 'Antanambao'),
  ('Vakinankaratra', 'Mandoto'),
  ('Vakinankaratra', 'Betsohana'),
  ('Vakinankaratra', 'Antanambao Ambary'),
  ('Vakinankaratra', 'Anjoma Ramartina'),
  ('Vakinankaratra', 'Ankazomiriotra'),
  ('Vakinankaratra', 'Fidirana'),
  ('Vakinankaratra', 'Vasiana'),
  ('Vakinankaratra', 'Vinany'),
  ('Itasy', 'Arivonimamo I'),
  ('Itasy', 'Arivonimamo II'),
  ('Itasy', 'Ambohitrambo'),
  ('Itasy', 'Ampahimanga'),
  ('Itasy', 'Amboanana'),
  ('Itasy', 'Morafeno'),
  ('Itasy', 'Imerintsiatosika'),
  ('Itasy', 'Morarano'),
  ('Itasy', 'Ambatomirahavavy'),
  ('Itasy', 'Ambatomanga'),
  ('Itasy', 'Manalalondo'),
  ('Itasy', 'Antenimbe'),
  ('Itasy', 'Alakamisikely'),
  ('Itasy', 'Mahatsinjo Est'),
  ('Itasy', 'Marofangady'),
  ('Itasy', 'Rambolamasoandro Andranomiely'),
  ('Itasy', 'Ambohimandry'),
  ('Itasy', 'Antambolo'),
  ('Itasy', 'Ambohimasina'),
  ('Itasy', 'Ambohipandrano'),
  ('Itasy', 'Miandrandra'),
  ('Itasy', 'Miantsoarivo'),
  ('Itasy', 'Miarinarivo I'),
  ('Itasy', 'Miarinarivo II'),
  ('Itasy', 'Ambatomanjaka'),
  ('Itasy', 'Manazary'),
  ('Itasy', 'Antoby Est'),
  ('Itasy', 'Soamahamanina'),
  ('Itasy', 'Analavory'),
  ('Itasy', 'Alatsinainikely'),
  ('Itasy', 'Mandiavato'),
  ('Itasy', 'Anosibe Ifanja'),
  ('Itasy', 'Sarobaratra Ifanja'),
  ('Itasy', 'Zoma Bealoka'),
  ('Itasy', 'Soavimbazaha'),
  ('Itasy', 'Andolofotsy'),
  ('Itasy', 'Soavinandriana'),
  ('Itasy', 'Dondona'),
  ('Itasy', 'Ampary'),
  ('Itasy', 'Mananasy'),
  ('Itasy', 'Masindray'),
  ('Itasy', 'Amparibohitra'),
  ('Itasy', 'Ampefy'),
  ('Itasy', 'Antanetibe'),
  ('Itasy', 'Amparaky'),
  ('Itasy', 'Amberomanga'),
  ('Itasy', 'Ankaranana'),
  ('Itasy', 'Mahavelona'),
  ('Itasy', 'Ankisabe'),
  ('Itasy', 'Ambatoasana Centre'),
  ('Itasy', 'Tamponala'),
  ('Bongolava', 'Tsiroanomandidy Ville'),
  ('Bongolava', 'Tsiroanomandidy Fihaonana'),
  ('Bongolava', 'Ambatolampy'),
  ('Bongolava', 'Maritampona'),
  ('Bongolava', 'Bevato'),
  ('Bongolava', 'Ankadinondry Sakay'),
  ('Bongolava', 'Ankerana Avaratra'),
  ('Bongolava', 'Miandrarivo'),
  ('Bongolava', 'Tsinjoarivo Imanga'),
  ('Bongolava', 'Soanierana'),
  ('Bongolava', 'Anosy'),
  ('Bongolava', 'Ambararatabe'),
  ('Bongolava', 'Belobaka'),
  ('Bongolava', 'Ambalanirana'),
  ('Bongolava', 'Mahasolo'),
  ('Bongolava', 'Bemahatazana'),
  ('Bongolava', 'Fierenana'),
  ('Bongolava', 'Maroharona'),
  ('Bongolava', 'Fenoarivo Centre'),
  ('Bongolava', 'Firavahana'),
  ('Bongolava', 'Morarano Maritampona'),
  ('Bongolava', 'Kiranomena'),
  ('Bongolava', 'Tsinjoarivo 22'),
  ('Bongolava', 'Mahajeby'),
  ('Bongolava', 'Ambohitromby'),
  ('Bongolava', 'Ambatomainty Atsimo'),
  ('Haute Matsiatra', 'Tanana Ambony'),
  ('Haute Matsiatra', 'Tanana Ambany'),
  ('Haute Matsiatra', 'Andrainjato Avaratra'),
  ('Haute Matsiatra', 'Andrainjato Sud'),
  ('Haute Matsiatra', 'Manolafaka'),
  ('Haute Matsiatra', 'Lalazana'),
  ('Haute Matsiatra', 'Vatosola'),
  ('Haute Matsiatra', 'Ambalavao'),
  ('Haute Matsiatra', 'Manamisoa'),
  ('Haute Matsiatra', 'Iarintsena'),
  ('Haute Matsiatra', 'Ambohimandroso'),
  ('Haute Matsiatra', 'Andrainjato'),
  ('Haute Matsiatra', 'Anjoma'),
  ('Haute Matsiatra', 'Kirano'),
  ('Haute Matsiatra', 'Sendrisoa'),
  ('Haute Matsiatra', 'Besoa'),
  ('Haute Matsiatra', 'Mahazony'),
  ('Haute Matsiatra', 'Ambinanindovoka'),
  ('Haute Matsiatra', 'Ankaramena'),
  ('Haute Matsiatra', 'Ambinaniroa'),
  ('Haute Matsiatra', 'Ambohimahamasina'),
  ('Haute Matsiatra', 'Miarinarivo'),
  ('Haute Matsiatra', 'Vohitsaoka'),
  ('Haute Matsiatra', 'Ankerana'),
  ('Haute Matsiatra', 'Manandroy'),
  ('Haute Matsiatra', 'Ambalakindresy'),
  ('Haute Matsiatra', 'Ankafina Tsarafidy'),
  ('Haute Matsiatra', 'Sahave'),
  ('Haute Matsiatra', 'Morafeno'),
  ('Haute Matsiatra', 'Ikalalao'),
  ('Haute Matsiatra', 'Vohiposa'),
  ('Haute Matsiatra', 'Ambatosoa'),
  ('Haute Matsiatra', 'Isaka'),
  ('Haute Matsiatra', 'Vohitrarivo'),
  ('Haute Matsiatra', 'Ambohinamboarina'),
  ('Haute Matsiatra', 'Sahatona'),
  ('Haute Matsiatra', 'Camp Robin'),
  ('Haute Matsiatra', 'Befeta'),
  ('Haute Matsiatra', 'Fiadanana'),
  ('Haute Matsiatra', 'Ikalamavony'),
  ('Haute Matsiatra', 'Mangidy'),
  ('Haute Matsiatra', 'Solila'),
  ('Haute Matsiatra', 'Ambatomainty'),
  ('Haute Matsiatra', 'Fitampito'),
  ('Haute Matsiatra', 'Tanamarina Sakay'),
  ('Haute Matsiatra', 'Tsitondroina'),
  ('Haute Matsiatra', 'Tanamarina Bekisopa'),
  ('Haute Matsiatra', 'Andrainjato Centre'),
  ('Haute Matsiatra', 'Andrainjato Est'),
  ('Haute Matsiatra', 'Ambalakely'),
  ('Haute Matsiatra', 'Ivoamba'),
  ('Haute Matsiatra', 'Taindambo'),
  ('Haute Matsiatra', 'Mahatsinjony'),
  ('Haute Matsiatra', 'Sahambavy'),
  ('Haute Matsiatra', 'Ambalamahasoa'),
  ('Haute Matsiatra', 'Alakamisy Ambohimaha'),
  ('Haute Matsiatra', 'Androy'),
  ('Haute Matsiatra', 'Alatsinainy Ialamarina'),
  ('Haute Matsiatra', 'Fandrandava'),
  ('Haute Matsiatra', 'Ialananindro'),
  ('Haute Matsiatra', 'Mahasoabe'),
  ('Haute Matsiatra', 'Vinanitelo'),
  ('Haute Matsiatra', 'Alakamisy Itenina'),
  ('Haute Matsiatra', 'Talata Ampano'),
  ('Haute Matsiatra', 'Ihazoara'),
  ('Haute Matsiatra', 'Ankaromalaza Mifanasoa'),
  ('Haute Matsiatra', 'Vohimarina'),
  ('Haute Matsiatra', 'Maneva'),
  ('Haute Matsiatra', 'Vohitrafeno'),
  ('Haute Matsiatra', 'Andranovorivato'),
  ('Haute Matsiatra', 'Vohibato Ouest'),
  ('Haute Matsiatra', 'Andranomiditra'),
  ('Haute Matsiatra', 'Soaindrana'),
  ('Haute Matsiatra', 'Mahaditra'),
  ('Haute Matsiatra', 'Isorana'),
  ('Haute Matsiatra', 'Anjoma Itsara'),
  ('Haute Matsiatra', 'Andoharanomaitso'),
  ('Haute Matsiatra', 'Ambondrona'),
  ('Haute Matsiatra', 'Ambalamidera II'),
  ('Haute Matsiatra', 'Ankarinarivo Manirisoa'),
  ('Haute Matsiatra', 'Soatanana'),
  ('Haute Matsiatra', 'Nasandratrony'),
  ('Haute Matsiatra', 'Mahazoarivo'),
  ('Haute Matsiatra', 'Fanjakana'),
  ('Haute Matsiatra', 'Iavonomby Vohibola'),
  ('Amoron I Mania', 'Ambatofinandrahana'),
  ('Amoron I Mania', 'Itremo'),
  ('Amoron I Mania', 'Fenoarivo'),
  ('Amoron I Mania', 'Soavina'),
  ('Amoron I Mania', 'Ambondromisotra'),
  ('Amoron I Mania', 'Ambatomifanongoa'),
  ('Amoron I Mania', 'Amborompotsy'),
  ('Amoron I Mania', 'Mandrosonoro'),
  ('Amoron I Mania', 'Mangataboahangy'),
  ('Amoron I Mania', 'Ambositra I'),
  ('Amoron I Mania', 'Ambositra II'),
  ('Amoron I Mania', 'Ankazoambo'),
  ('Amoron I Mania', 'Ivony Miaramiasa'),
  ('Amoron I Mania', 'Andina'),
  ('Amoron I Mania', 'Imerina Imady'),
  ('Amoron I Mania', 'Ivato'),
  ('Amoron I Mania', 'Tsarasaotra'),
  ('Amoron I Mania', 'Marosoa'),
  ('Amoron I Mania', 'Fahizay'),
  ('Amoron I Mania', 'Alakamisy Ambohijato'),
  ('Amoron I Mania', 'Kianjandrakefina'),
  ('Amoron I Mania', 'Ambalamanakana'),
  ('Amoron I Mania', 'Ilaka Centre'),
  ('Amoron I Mania', 'Ihadilanana'),
  ('Amoron I Mania', 'Ambatofitorahana'),
  ('Amoron I Mania', 'Antoetra'),
  ('Amoron I Mania', 'Mahazina Ambohipierenana'),
  ('Amoron I Mania', 'Sahatsiho Ambohimanjaka'),
  ('Amoron I Mania', 'Ambohimitombo I'),
  ('Amoron I Mania', 'Ambohimitombo II'),
  ('Amoron I Mania', 'Ambinanindrano'),
  ('Amoron I Mania', 'Vohidahy'),
  ('Amoron I Mania', 'Fandriana'),
  ('Amoron I Mania', 'Milamaina'),
  ('Amoron I Mania', 'Sahamadio Fisakana'),
  ('Amoron I Mania', 'Fiadanana'),
  ('Amoron I Mania', 'Tsarazaza'),
  ('Amoron I Mania', 'Tatamalaza'),
  ('Amoron I Mania', 'Ankarinoro'),
  ('Amoron I Mania', 'Sandrandahy'),
  ('Amoron I Mania', 'Mahazoarivo'),
  ('Amoron I Mania', 'Miarinavaratra'),
  ('Amoron I Mania', 'Betsimisotra'),
  ('Amoron I Mania', 'Alakamisy Ambohimahazo'),
  ('Amoron I Mania', 'Imito'),
  ('Amoron I Mania', 'Ambovombe Centre'),
  ('Amoron I Mania', 'Ambohimahazo'),
  ('Amoron I Mania', 'Anjoma Nandihizana'),
  ('Amoron I Mania', 'Ambohimilanja'),
  ('Amoron I Mania', 'Talata Vohimena'),
  ('Amoron I Mania', 'Ambatomarina'),
  ('Amoron I Mania', 'Andakatany'),
  ('Vatovavy', 'Ifanadiana'),
  ('Vatovavy', 'Antaretra (Ifanadiana)'),
  ('Vatovavy', 'Tsaratanana'),
  ('Vatovavy', 'Ranomafana'),
  ('Vatovavy', 'Kelilalina'),
  ('Vatovavy', 'Androrangavola (Ifanadiana)'),
  ('Vatovavy', 'Marotoko'),
  ('Vatovavy', 'Ambohimiera'),
  ('Vatovavy', 'Antsindra'),
  ('Vatovavy', 'Ambohimanga Du Sud'),
  ('Vatovavy', 'Analampasina'),
  ('Vatovavy', 'Fasintsara'),
  ('Vatovavy', 'Maroharatra'),
  ('Vatovavy', 'Nosy Varika'),
  ('Vatovavy', 'Ambahy'),
  ('Vatovavy', 'Andara'),
  ('Vatovavy', 'Fiadanana'),
  ('Vatovavy', 'Ambodirian''i Sahafary'),
  ('Vatovavy', 'Sahavato'),
  ('Vatovavy', 'Vohilava (Nosy-Varika)'),
  ('Vatovavy', 'Vohitrandriana'),
  ('Vatovavy', 'Vohidroa'),
  ('Vatovavy', 'Ambakobe'),
  ('Vatovavy', 'Soavina'),
  ('Vatovavy', 'Ambodilafa'),
  ('Vatovavy', 'Androrangavola (Nosy-Varika)'),
  ('Vatovavy', 'Ampasinambo'),
  ('Vatovavy', 'Antanambao'),
  ('Vatovavy', 'Angodongodona'),
  ('Vatovavy', 'Befody'),
  ('Vatovavy', 'Ambodiara'),
  ('Vatovavy', 'Mananjary'),
  ('Vatovavy', 'Tsaravary'),
  ('Vatovavy', 'Ankatafana'),
  ('Vatovavy', 'Mahatsara Sud'),
  ('Vatovavy', 'Tsiatosika'),
  ('Vatovavy', 'Mahatsara Iefaka'),
  ('Vatovavy', 'Marokarima'),
  ('Vatovavy', 'Morafeno'),
  ('Vatovavy', 'Antsenavolo'),
  ('Vatovavy', 'Marosangy'),
  ('Vatovavy', 'Ambohimiarina II'),
  ('Vatovavy', 'Andranambolava'),
  ('Vatovavy', 'Vohilava (Mananjary)'),
  ('Vatovavy', 'Mahela'),
  ('Vatovavy', 'Ambohitsara Est'),
  ('Vatovavy', 'Mahavoky Nord'),
  ('Vatovavy', 'Andonabe'),
  ('Vatovavy', 'Ambohinihaonana'),
  ('Vatovavy', 'Marofototra'),
  ('Vatovavy', 'Andranomavo'),
  ('Vatovavy', 'Vatohandrina'),
  ('Vatovavy', 'Ambalahosy Nord'),
  ('Vatovavy', 'Ambodinonoka'),
  ('Vatovavy', 'Antaretra (Mananjary)'),
  ('Vatovavy', 'Kianjavato'),
  ('Vatovavy', 'Sandrohy'),
  ('Vatovavy', 'Anosimparihy'),
  ('Vatovavy', 'Manakana Nord'),
  ('Vatovavy', 'Namorona'),
  ('Fitovinany', 'Manakara'),
  ('Fitovinany', 'Tataho'),
  ('Fitovinany', 'Mangatsiotra'),
  ('Fitovinany', 'Marofarihy'),
  ('Fitovinany', 'Anosiala'),
  ('Fitovinany', 'Ambila'),
  ('Fitovinany', 'Sorombo'),
  ('Fitovinany', 'Mizilo Gara'),
  ('Fitovinany', 'Ambohitsara M'),
  ('Fitovinany', 'Sahasinaka'),
  ('Fitovinany', 'Sahanambohitra'),
  ('Fitovinany', 'Ambahatrazo'),
  ('Fitovinany', 'Amboanjo'),
  ('Fitovinany', 'Anorombato'),
  ('Fitovinany', 'Vohimasy'),
  ('Fitovinany', 'Lokomby'),
  ('Fitovinany', 'Vatana'),
  ('Fitovinany', 'Sakoana'),
  ('Fitovinany', 'Ambahive'),
  ('Fitovinany', 'Ambandrika'),
  ('Fitovinany', 'Ambalaroka'),
  ('Fitovinany', 'Vohimanitra'),
  ('Fitovinany', 'Mitanty'),
  ('Fitovinany', 'Analavory'),
  ('Fitovinany', 'Bekatra'),
  ('Fitovinany', 'Vinanitelo'),
  ('Fitovinany', 'Ampasimanjeva'),
  ('Fitovinany', 'Ambotaka'),
  ('Fitovinany', 'Nihaonana'),
  ('Fitovinany', 'Mavorano'),
  ('Fitovinany', 'Vohimasina Nord'),
  ('Fitovinany', 'Vohimasina Sud'),
  ('Fitovinany', 'Betampona'),
  ('Fitovinany', 'Vohilava'),
  ('Fitovinany', 'Fenomby'),
  ('Fitovinany', 'Ambalavero'),
  ('Fitovinany', 'Amborondra'),
  ('Fitovinany', 'Mahabako'),
  ('Fitovinany', 'Onilahy'),
  ('Fitovinany', 'Mahamaibe'),
  ('Fitovinany', 'Kianjanomby'),
  ('Fitovinany', 'Ampasimpotsy Sud'),
  ('Fitovinany', 'Anteza'),
  ('Fitovinany', 'Saharefo'),
  ('Fitovinany', 'Ampasimboraka'),
  ('Fitovinany', 'Ikongo'),
  ('Fitovinany', 'Ambolomadinika'),
  ('Fitovinany', 'Ambatofotsy'),
  ('Fitovinany', 'Belemoka'),
  ('Fitovinany', 'Maromiandra'),
  ('Fitovinany', 'Manampatrana'),
  ('Fitovinany', 'Ambinanitromby'),
  ('Fitovinany', 'Ifanirea'),
  ('Fitovinany', 'Tanakambana'),
  ('Fitovinany', 'Sahalanona'),
  ('Fitovinany', 'Tolongoina'),
  ('Fitovinany', 'Ambohimisafy'),
  ('Fitovinany', 'Vohipeno'),
  ('Fitovinany', 'Vohitrindry'),
  ('Fitovinany', 'Vohindava'),
  ('Fitovinany', 'Ivato'),
  ('Fitovinany', 'Savana'),
  ('Fitovinany', 'Anoloka'),
  ('Fitovinany', 'Mahabo'),
  ('Fitovinany', 'Ankarimbary'),
  ('Fitovinany', 'Lanivo'),
  ('Fitovinany', 'Nato'),
  ('Fitovinany', 'Mahasoabe'),
  ('Fitovinany', 'Onjatsy'),
  ('Fitovinany', 'Vohilany'),
  ('Fitovinany', 'Andemaka'),
  ('Fitovinany', 'Ifatsy'),
  ('Fitovinany', 'Antananabo'),
  ('Fitovinany', 'Ilakatra'),
  ('Fitovinany', 'Sahalava'),
  ('Fitovinany', 'Mahazoarivo'),
  ('Ihorombe', 'Ihosy'),
  ('Ihorombe', 'Ankily'),
  ('Ihorombe', 'Ambia'),
  ('Ihorombe', 'Tolohomiady'),
  ('Ihorombe', 'Irina'),
  ('Ihorombe', 'Sahambano'),
  ('Ihorombe', 'Analaliry'),
  ('Ihorombe', 'Mahasoa'),
  ('Ihorombe', 'Ambatolahy'),
  ('Ihorombe', 'Soamatasy'),
  ('Ihorombe', 'Zazafotsy'),
  ('Ihorombe', 'Antsoha'),
  ('Ihorombe', 'Sakalalina'),
  ('Ihorombe', 'Satrokala'),
  ('Ihorombe', 'Andiolava'),
  ('Ihorombe', 'Analavoka'),
  ('Ihorombe', 'Ranohira'),
  ('Ihorombe', 'Ilakaka'),
  ('Ihorombe', 'Menamaty Iloto'),
  ('Ihorombe', 'Ivohibe'),
  ('Ihorombe', 'Antambohobe'),
  ('Ihorombe', 'Maropaika'),
  ('Ihorombe', 'Ivongo'),
  ('Ihorombe', 'Iakora'),
  ('Ihorombe', 'Ranotsara Nord'),
  ('Ihorombe', 'Begogo'),
  ('Atsimo Atsinanana', 'Farafangana'),
  ('Atsimo Atsinanana', 'Vohimasy'),
  ('Atsimo Atsinanana', 'Anosivelo'),
  ('Atsimo Atsinanana', 'Anosy Tsararafa'),
  ('Atsimo Atsinanana', 'Vohitromby'),
  ('Atsimo Atsinanana', 'Ivandrika'),
  ('Atsimo Atsinanana', 'Manambotra Atsimo'),
  ('Atsimo Atsinanana', 'Mahavelo (Farafangana)'),
  ('Atsimo Atsinanana', 'Mahafasa Centre'),
  ('Atsimo Atsinanana', 'Amporoforo'),
  ('Atsimo Atsinanana', 'Iabohazo'),
  ('Atsimo Atsinanana', 'Tangainony'),
  ('Atsimo Atsinanana', 'Beretra Bevoay'),
  ('Atsimo Atsinanana', 'Ambohigogo'),
  ('Atsimo Atsinanana', 'Maheriraty'),
  ('Atsimo Atsinanana', 'Mahabo Mananivo'),
  ('Atsimo Atsinanana', 'Ambohimandroso'),
  ('Atsimo Atsinanana', 'Ankarana Miraihina'),
  ('Atsimo Atsinanana', 'Evato'),
  ('Atsimo Atsinanana', 'Etrotroka Atsimo'),
  ('Atsimo Atsinanana', 'Ambalavato Nord'),
  ('Atsimo Atsinanana', 'Efatsy'),
  ('Atsimo Atsinanana', 'Tovona'),
  ('Atsimo Atsinanana', 'Ambalatany'),
  ('Atsimo Atsinanana', 'Namohora Iaborano'),
  ('Atsimo Atsinanana', 'Sahamadio'),
  ('Atsimo Atsinanana', 'Fenoarivo'),
  ('Atsimo Atsinanana', 'Antseranambe'),
  ('Atsimo Atsinanana', 'Ihorombe'),
  ('Atsimo Atsinanana', 'Ambalavato Antevato'),
  ('Atsimo Atsinanana', 'Vohilengo'),
  ('Atsimo Atsinanana', 'Marovandrika'),
  ('Atsimo Atsinanana', 'Vangaindrano'),
  ('Atsimo Atsinanana', 'Ampasimalemy'),
  ('Atsimo Atsinanana', 'Tsianofana'),
  ('Atsimo Atsinanana', 'Bekaraoky'),
  ('Atsimo Atsinanana', 'Tsiately'),
  ('Atsimo Atsinanana', 'Soamanova'),
  ('Atsimo Atsinanana', 'Lopary'),
  ('Atsimo Atsinanana', 'Bema'),
  ('Atsimo Atsinanana', 'Vohitrambo'),
  ('Atsimo Atsinanana', 'Anilobe'),
  ('Atsimo Atsinanana', 'Lohafary'),
  ('Atsimo Atsinanana', 'Ampataka'),
  ('Atsimo Atsinanana', 'Matanga'),
  ('Atsimo Atsinanana', 'Masianaka'),
  ('Atsimo Atsinanana', 'Vohipaho'),
  ('Atsimo Atsinanana', 'Marokibo'),
  ('Atsimo Atsinanana', 'Ranomena'),
  ('Atsimo Atsinanana', 'Ambongo'),
  ('Atsimo Atsinanana', 'Ambatolava'),
  ('Atsimo Atsinanana', 'Iara'),
  ('Atsimo Atsinanana', 'Bevata'),
  ('Atsimo Atsinanana', 'Karimbary'),
  ('Atsimo Atsinanana', 'Manambondro'),
  ('Atsimo Atsinanana', 'Fenoambany'),
  ('Atsimo Atsinanana', 'Isahara'),
  ('Atsimo Atsinanana', 'Vohimalaza'),
  ('Atsimo Atsinanana', 'Vatanato'),
  ('Atsimo Atsinanana', 'Amparihy Est'),
  ('Atsimo Atsinanana', 'Sandravinany'),
  ('Atsimo Atsinanana', 'Nosifeno'),
  ('Atsimo Atsinanana', 'Ankazovelo'),
  ('Atsimo Atsinanana', 'Andranolalina'),
  ('Atsimo Atsinanana', 'Maliorano'),
  ('Atsimo Atsinanana', 'Ivondro'),
  ('Atsimo Atsinanana', 'Soakibany'),
  ('Atsimo Atsinanana', 'Vondrozo'),
  ('Atsimo Atsinanana', 'Manambidala'),
  ('Atsimo Atsinanana', 'Anandravy'),
  ('Atsimo Atsinanana', 'Mahatsinjo'),
  ('Atsimo Atsinanana', 'Mahazoarivo'),
  ('Atsimo Atsinanana', 'Iamonta'),
  ('Atsimo Atsinanana', 'Vohimary'),
  ('Atsimo Atsinanana', 'Antokonala'),
  ('Atsimo Atsinanana', 'Ambohimana'),
  ('Atsimo Atsinanana', 'Karianga'),
  ('Atsimo Atsinanana', 'Manato'),
  ('Atsimo Atsinanana', 'Ivato'),
  ('Atsimo Atsinanana', 'Mahavelo (Vondrozo)'),
  ('Atsimo Atsinanana', 'Andakana'),
  ('Atsimo Atsinanana', 'Moroteza'),
  ('Atsimo Atsinanana', 'Vohiboreka'),
  ('Atsimo Atsinanana', 'Befotaka Sud'),
  ('Atsimo Atsinanana', 'Ranotsara Sud'),
  ('Atsimo Atsinanana', 'Beharena'),
  ('Atsimo Atsinanana', 'Bekofafa Sud'),
  ('Atsinanana', 'Ambodimanga'),
  ('Atsinanana', 'Anjoma'),
  ('Atsinanana', 'Morarano'),
  ('Atsinanana', 'Tanambao V'),
  ('Atsinanana', 'Ankirihiry'),
  ('Atsinanana', 'Brickaville'),
  ('Atsinanana', 'Vohitranivona'),
  ('Atsinanana', 'Anivorano Est'),
  ('Atsinanana', 'Mahatsara'),
  ('Atsinanana', 'Andovoranto'),
  ('Atsinanana', 'Ambinaninony'),
  ('Atsinanana', 'Fetraomby'),
  ('Atsinanana', 'Vohipeno Razanaka'),
  ('Atsinanana', 'Ranomafana Est'),
  ('Atsinanana', 'Ampasimbe'),
  ('Atsinanana', 'Fanasana'),
  ('Atsinanana', 'Ambalarondra'),
  ('Atsinanana', 'Maroseranana'),
  ('Atsinanana', 'Lohariandava'),
  ('Atsinanana', 'Andekaleka'),
  ('Atsinanana', 'Ambohimanana'),
  ('Atsinanana', 'Anjahamana'),
  ('Atsinanana', 'Vatomandry'),
  ('Atsinanana', 'Ambodivoananto'),
  ('Atsinanana', 'Maintinandry'),
  ('Atsinanana', 'Tanambao Vahatrakaka'),
  ('Atsinanana', 'Tsarasambo'),
  ('Atsinanana', 'Sahamatevina'),
  ('Atsinanana', 'Antanambao Mahatsara'),
  ('Atsinanana', 'Iamborano'),
  ('Atsinanana', 'Ambalavolo'),
  ('Atsinanana', 'Amboditavolo'),
  ('Atsinanana', 'Niherenana'),
  ('Atsinanana', 'Ilaka Est'),
  ('Atsinanana', 'Niarovana Caroline'),
  ('Atsinanana', 'Tsivangiana'),
  ('Atsinanana', 'Ampasimazava'),
  ('Atsinanana', 'Ampasimadinika'),
  ('Atsinanana', 'Ifasina I'),
  ('Atsinanana', 'Ambalabe'),
  ('Atsinanana', 'Ifasina II'),
  ('Atsinanana', 'Mahanoro'),
  ('Atsinanana', 'Betsizaraina'),
  ('Atsinanana', 'Tsaravinany'),
  ('Atsinanana', 'Ambodiharina'),
  ('Atsinanana', 'Manjakandriana'),
  ('Atsinanana', 'Masomeloka'),
  ('Atsinanana', 'Ambinanidilana'),
  ('Atsinanana', 'Ambodibonara'),
  ('Atsinanana', 'Ankazotsifantatra'),
  ('Atsinanana', 'Ambinanindrano'),
  ('Atsinanana', 'Befotaka'),
  ('Atsinanana', 'Marolambo'),
  ('Atsinanana', 'Betampona'),
  ('Atsinanana', 'Tanambao Rabemanana'),
  ('Atsinanana', 'Andonabe Sud'),
  ('Atsinanana', 'Ambalapaiso II'),
  ('Atsinanana', 'Ambodivoangy'),
  ('Atsinanana', 'Ambohimilanja'),
  ('Atsinanana', 'Ambatofisaka II'),
  ('Atsinanana', 'Androrangavola'),
  ('Atsinanana', 'Anosiarivo I'),
  ('Atsinanana', 'Amboasary'),
  ('Atsinanana', 'Lohavanana'),
  ('Atsinanana', 'Ambodinonoka'),
  ('Atsinanana', 'Sahakevo'),
  ('Atsinanana', 'Toamasina Suburbaine'),
  ('Atsinanana', 'Antetezambaro'),
  ('Atsinanana', 'Fanandrana'),
  ('Atsinanana', 'Ambodiriana'),
  ('Atsinanana', 'Ampasimadinika Manambolo'),
  ('Atsinanana', 'Amboditandroroho'),
  ('Atsinanana', 'Mahavelona (Foulpointe)'),
  ('Atsinanana', 'Sahambala'),
  ('Atsinanana', 'Ambodilazana'),
  ('Atsinanana', 'Ampasimbe Onibe'),
  ('Atsinanana', 'Mangabe'),
  ('Atsinanana', 'Amporoforo'),
  ('Atsinanana', 'Antenina'),
  ('Atsinanana', 'Andondabe'),
  ('Atsinanana', 'Ampisokina'),
  ('Atsinanana', 'Andranobolaha'),
  ('Atsinanana', 'Fito'),
  ('Atsinanana', 'Antanambao Manampontsy'),
  ('Atsinanana', 'Mahela'),
  ('Atsinanana', 'Saivaza'),
  ('Atsinanana', 'Antanandehibe'),
  ('Atsinanana', 'Manakana'),
  ('Analanjirofo', 'Sainte Marie'),
  ('Ambatosoa', 'Maroantsetra'),
  ('Ambatosoa', 'Anjanazana'),
  ('Ambatosoa', 'Manambolo'),
  ('Ambatosoa', 'Andranofotsy'),
  ('Ambatosoa', 'Antakotako'),
  ('Ambatosoa', 'Ankofa'),
  ('Ambatosoa', 'Ambinanitelo'),
  ('Ambatosoa', 'Anjahana'),
  ('Ambatosoa', 'Ambanizana'),
  ('Ambatosoa', 'Mahalevona'),
  ('Ambatosoa', 'Voloina'),
  ('Ambatosoa', 'Ankofabe'),
  ('Ambatosoa', 'Antsirabe Sahatany'),
  ('Ambatosoa', 'Rantabe'),
  ('Ambatosoa', 'Morafeno'),
  ('Ambatosoa', 'Androndrono'),
  ('Ambatosoa', 'Ambodimanga Rantabe'),
  ('Ambatosoa', 'Anandrivola'),
  ('Analanjirofo', 'Mananara Avaratra'),
  ('Analanjirofo', 'Ambodivoanio'),
  ('Analanjirofo', 'Imorona'),
  ('Analanjirofo', 'Antanambaobe'),
  ('Analanjirofo', 'Antanananivo'),
  ('Analanjirofo', 'Manambolosy'),
  ('Analanjirofo', 'Ambodiampana (Mananara-Avaratra)'),
  ('Analanjirofo', 'Sandrakatsy'),
  ('Analanjirofo', 'Tanibe'),
  ('Analanjirofo', 'Ambatoharanana (Mananara-Avaratra)'),
  ('Analanjirofo', 'Fotsialanana'),
  ('Analanjirofo', 'Antanifotsy'),
  ('Analanjirofo', 'Ambodiampana (Soanierana Ivongo)'),
  ('Boeny', 'Andranofasika'),
  ('Boeny', 'Madirovalo'),
  ('Boeny', 'Anjiajia'),
  ('Sofia', 'Andranomeva'),
  ('Sofia', 'Amparihy'),
  ('Sofia', 'Leanja'),
  ('Sofia', 'Marovato'),
  ('Sofia', 'Ambodimahabibo'),
  ('Sofia', 'Ambodivongo'),
  ('Melaky', 'Besalampy'),
  ('Melaky', 'Ampako'),
  ('Melaky', 'Marovoay Sud'),
  ('Atsimo Andrefana', 'Mandronarivo'),
  ('Atsimo Andrefana', 'Tanamary'),
  ('Atsimo Andrefana', 'Sakena'),
  ('Atsimo Andrefana', 'Antanimieva'),
  ('Atsimo Andrefana', 'Basibasy'),
  ('Atsimo Andrefana', 'Ankazoabo Sud'),
  ('Analanjirofo', 'Antanambe'),
  ('Analanjirofo', 'Saromaona'),
  ('Analanjirofo', 'Vanono'),
  ('Analanjirofo', 'Andasibe I'),
  ('Analanjirofo', 'Fenerive Est'),
  ('Analanjirofo', 'Ambodimanga II'),
  ('Analanjirofo', 'Mahambo'),
  ('Analanjirofo', 'Ampasina Maningory'),
  ('Analanjirofo', 'Ambatoharanana (Fenerive Est)'),
  ('Analanjirofo', 'Vohilengo'),
  ('Analanjirofo', 'Saranambana'),
  ('Analanjirofo', 'Ampasimbe Manantsatrana'),
  ('Analanjirofo', 'Miorimivalana'),
  ('Analanjirofo', 'Vohipeno'),
  ('Analanjirofo', 'Antsiatsiaka'),
  ('Analanjirofo', 'Mahanoro'),
  ('Analanjirofo', 'Vavatenina'),
  ('Analanjirofo', 'Maromitety'),
  ('Analanjirofo', 'Ambohibe'),
  ('Analanjirofo', 'Ampasimazava'),
  ('Analanjirofo', 'Anjahambe'),
  ('Analanjirofo', 'Ambatoharanana (Vavatenina)'),
  ('Analanjirofo', 'Andasibe'),
  ('Analanjirofo', 'Miarinarivo'),
  ('Analanjirofo', 'Sahatavy'),
  ('Analanjirofo', 'Ambodimangavalo'),
  ('Analanjirofo', 'Soanierana Ivongo'),
  ('Analanjirofo', 'Andapafito'),
  ('Analanjirofo', 'Ambahoabe'),
  ('Analanjirofo', 'Manompana'),
  ('Analanjirofo', 'Antenina'),
  ('Alaotra Mangoro', 'Amparafaravola'),
  ('Alaotra Mangoro', 'Bedidy'),
  ('Alaotra Mangoro', 'Ambohimandroso'),
  ('Alaotra Mangoro', 'Sahamamy'),
  ('Alaotra Mangoro', 'Ambatomainty'),
  ('Alaotra Mangoro', 'Ampasikely'),
  ('Alaotra Mangoro', 'Andrebakely Sud'),
  ('Alaotra Mangoro', 'Ambohitrarivo'),
  ('Alaotra Mangoro', 'Anororo'),
  ('Alaotra Mangoro', 'Morarano Chrome'),
  ('Alaotra Mangoro', 'Ranomainty'),
  ('Alaotra Mangoro', 'Ambohijanahary'),
  ('Alaotra Mangoro', 'Tanambe'),
  ('Alaotra Mangoro', 'Beanana'),
  ('Alaotra Mangoro', 'Vohitsara'),
  ('Alaotra Mangoro', 'Amboavory'),
  ('Alaotra Mangoro', 'Andilana Nord'),
  ('Alaotra Mangoro', 'Ambodimanga'),
  ('Alaotra Mangoro', 'Vohimena'),
  ('Alaotra Mangoro', 'Andrebakely Nord'),
  ('Alaotra Mangoro', 'Ambatondrazaka'),
  ('Alaotra Mangoro', 'Feramanga Nord'),
  ('Alaotra Mangoro', 'Ambatondrazaka Suburbaine'),
  ('Alaotra Mangoro', 'Ambandrika'),
  ('Alaotra Mangoro', 'Ampitatsimo'),
  ('Alaotra Mangoro', 'Ambohitsilaozana'),
  ('Alaotra Mangoro', 'Ilafy'),
  ('Alaotra Mangoro', 'Manakambahiny Andrefana'),
  ('Alaotra Mangoro', 'Antsangasanga'),
  ('Alaotra Mangoro', 'Ambatosoratra'),
  ('Alaotra Mangoro', 'Andilanatoby'),
  ('Alaotra Mangoro', 'Bejofo'),
  ('Alaotra Mangoro', 'Didy'),
  ('Alaotra Mangoro', 'Imerimandroso'),
  ('Alaotra Mangoro', 'Amparihintsokatra'),
  ('Alaotra Mangoro', 'Antanandava (Ambatondrazaka)'),
  ('Alaotra Mangoro', 'Andromba'),
  ('Alaotra Mangoro', 'Manakambahiny Antsinanana'),
  ('Alaotra Mangoro', 'Soalazaina'),
  ('Alaotra Mangoro', 'Tanambao Besakay'),
  ('Alaotra Mangoro', 'Moramanga'),
  ('Alaotra Mangoro', 'Ambohibary'),
  ('Alaotra Mangoro', 'Ampasimpotsy Gara'),
  ('Alaotra Mangoro', 'Andasibe'),
  ('Alaotra Mangoro', 'Anosibe Ifody'),
  ('Alaotra Mangoro', 'Vodiriana'),
  ('Alaotra Mangoro', 'Morarano Gara'),
  ('Alaotra Mangoro', 'Belavabary'),
  ('Alaotra Mangoro', 'Sabotsy Anjiro'),
  ('Alaotra Mangoro', 'Ambohidronono'),
  ('Alaotra Mangoro', 'Beforona'),
  ('Alaotra Mangoro', 'Ambatovola'),
  ('Alaotra Mangoro', 'Lakato'),
  ('Alaotra Mangoro', 'Amboasary'),
  ('Alaotra Mangoro', 'Fierenana'),
  ('Alaotra Mangoro', 'Mandialaza'),
  ('Alaotra Mangoro', 'Antaniditra'),
  ('Alaotra Mangoro', 'Ampasipotsy Mandialaza'),
  ('Alaotra Mangoro', 'Antanandava (Moramanga)'),
  ('Alaotra Mangoro', 'Mangarivotra'),
  ('Alaotra Mangoro', 'Andaingo'),
  ('Alaotra Mangoro', 'Andilamena'),
  ('Alaotra Mangoro', 'Bemaitso'),
  ('Alaotra Mangoro', 'Antanimenabaka'),
  ('Alaotra Mangoro', 'Tanananifololahy'),
  ('Alaotra Mangoro', 'Maroadabo'),
  ('Alaotra Mangoro', 'Marovato'),
  ('Alaotra Mangoro', 'Miarinarivo'),
  ('Alaotra Mangoro', 'Maitsokely'),
  ('Alaotra Mangoro', 'Anosibe An''ala'),
  ('Alaotra Mangoro', 'Ampasimaneva'),
  ('Alaotra Mangoro', 'Ampandroantraka'),
  ('Alaotra Mangoro', 'Tratramarina'),
  ('Alaotra Mangoro', 'Antandrokomby'),
  ('Alaotra Mangoro', 'Ambalaomby'),
  ('Alaotra Mangoro', 'Niarovana Marosampanana'),
  ('Alaotra Mangoro', 'Tsaravinany'),
  ('Alaotra Mangoro', 'Longozabe'),
  ('Alaotra Mangoro', 'Ambatoharanana'),
  ('Boeny', 'Mahajanga'),
  ('Boeny', 'Mahabibo'),
  ('Boeny', 'Soalala'),
  ('Boeny', 'Ambohipaky'),
  ('Boeny', 'Andranomavo'),
  ('Boeny', 'Ambato Ambarimay'),
  ('Boeny', 'Ankijabe'),
  ('Boeny', 'Tsaramandroso'),
  ('Boeny', 'Ambondromamy'),
  ('Boeny', 'Ankirihitra'),
  ('Boeny', 'Andranomamy'),
  ('Boeny', 'Manerinerina'),
  ('Boeny', 'Sitampiky'),
  ('Boeny', 'Marovoay Ville'),
  ('Boeny', 'Marovoay Banlieue'),
  ('Boeny', 'Antanambao Andranolava'),
  ('Boeny', 'Anosinalainolona'),
  ('Boeny', 'Ambolomoty'),
  ('Boeny', 'Marovoay'),
  ('Boeny', 'Tsararano'),
  ('Boeny', 'Ankazomborona'),
  ('Boeny', 'Manaratsandry'),
  ('Boeny', 'Antanimasaka'),
  ('Boeny', 'Bemaharivo'),
  ('Boeny', 'Ankaraobato'),
  ('Boeny', 'Mitsinjo'),
  ('Boeny', 'Antseza'),
  ('Boeny', 'Antongomena Bevary'),
  ('Boeny', 'Matsakabanja'),
  ('Boeny', 'Katsepy'),
  ('Boeny', 'Bekipay'),
  ('Boeny', 'Ambarimaninga'),
  ('Boeny', 'Belobaka'),
  ('Boeny', 'Boanamary'),
  ('Boeny', 'Ambalakida'),
  ('Boeny', 'Betsako'),
  ('Boeny', 'Mariarano'),
  ('Boeny', 'Bekobay'),
  ('Boeny', 'Andranoboka'),
  ('Boeny', 'Mahajamba Usine'),
  ('Boeny', 'Ambalabe Befanjava'),
  ('Sofia', 'Port Berge'),
  ('Sofia', 'Ambanjabe'),
  ('Sofia', 'Tsaratanana I'),
  ('Sofia', 'Tsarahasina'),
  ('Sofia', 'Tsiningia'),
  ('Sofia', 'Ambodisakoana'),
  ('Sofia', 'Tsinjomitondraka'),
  ('Sofia', 'Maevaranohely'),
  ('Sofia', 'Port Berge II'),
  ('Sofia', 'Mandritsara'),
  ('Sofia', 'Antanandava'),
  ('Sofia', 'Antsoha'),
  ('Sofia', 'Tsaratanana'),
  ('Sofia', 'Kalandy'),
  ('Sofia', 'Antsirabe Centre'),
  ('Sofia', 'Antsiatsiaka'),
  ('Sofia', 'Amboaboa'),
  ('Sofia', 'Manampaneva'),
  ('Sofia', 'Ambarikorano'),
  ('Sofia', 'Andratamarina'),
  ('Sofia', 'Ambaripaika'),
  ('Sofia', 'Ambodiamontana Kianga'),
  ('Sofia', 'Ambalakirajy'),
  ('Sofia', 'Tsarajomoka'),
  ('Sofia', 'Antsatramidola'),
  ('Sofia', 'Ankiakabe-Fonoko'),
  ('Sofia', 'Marotandrano'),
  ('Sofia', 'Ambilombe'),
  ('Sofia', 'Andohajango'),
  ('Sofia', 'Anjiabe'),
  ('Sofia', 'Ambohisoa'),
  ('Sofia', 'Ampatakamaroreny'),
  ('Sofia', 'Ankiabe-Salohy'),
  ('Sofia', 'Pont Sofia'),
  ('Sofia', 'Ambodiadabo'),
  ('Sofia', 'Amborondolo'),
  ('Sofia', 'Antanambaon''amberina'),
  ('Sofia', 'Analalava'),
  ('Sofia', 'Ambarijeby Sud'),
  ('Sofia', 'Ambolobozo'),
  ('Sofia', 'Befotaka Nord'),
  ('Sofia', 'Ambaliha'),
  ('Sofia', 'Maromandia'),
  ('Sofia', 'Marovatolena'),
  ('Sofia', 'Andribavontsona'),
  ('Sofia', 'Angoaka Sud'),
  ('Sofia', 'Marovantaza'),
  ('Sofia', 'Ankaramy'),
  ('Sofia', 'Antonibe'),
  ('Sofia', 'Mahadrodroka'),
  ('Sofia', 'Befandriana Nord'),
  ('Sofia', 'Morafeno'),
  ('Sofia', 'Ambodimotso Sud'),
  ('Sofia', 'Tsiamalao'),
  ('Sofia', 'Maroamalona'),
  ('Sofia', 'Tsarahonenana'),
  ('Sofia', 'Antsakanalabe'),
  ('Sofia', 'Ambararata'),
  ('Sofia', 'Ambolidibe Est'),
  ('Sofia', 'Ankarongana'),
  ('Sofia', 'Antsakabary'),
  ('Sofia', 'Matsondakana'),
  ('Sofia', 'Antsohihy'),
  ('Sofia', 'Ankerika'),
  ('Sofia', 'Ampandriankilandy'),
  ('Sofia', 'Anjalazala'),
  ('Sofia', 'Anahidrano'),
  ('Sofia', 'Ambodimandresy'),
  ('Sofia', 'Anjiamangirana'),
  ('Sofia', 'Ambodimanary'),
  ('Sofia', 'Antsahabe'),
  ('Sofia', 'Ambodimadiro'),
  ('Sofia', 'Andreba'),
  ('Sofia', 'Maroala'),
  ('Sofia', 'Bealanana'),
  ('Sofia', 'Beandrarezona'),
  ('Sofia', 'Antananivo Haut'),
  ('Sofia', 'Antsamaka'),
  ('Sofia', 'Ambatosia'),
  ('Sofia', 'Ambodiampana'),
  ('Sofia', 'Ambatoriha Est'),
  ('Sofia', 'Ambovonomby'),
  ('Sofia', 'Analila'),
  ('Sofia', 'Anjozoromadosy'),
  ('Sofia', 'Mangindrano'),
  ('Sofia', 'Ambararatabe Nord'),
  ('Sofia', 'Ambodisikidy'),
  ('Sofia', 'Ambararata Sofia'),
  ('Sofia', 'Marotolana'),
  ('Sofia', 'Ambodiadabo M'),
  ('Sofia', 'Ankazotokana'),
  ('Sofia', 'Ambalaromba'),
  ('Sofia', 'Mampikony I'),
  ('Sofia', 'Mampikony II'),
  ('Sofia', 'Ambohitoaka'),
  ('Sofia', 'Ankiririky'),
  ('Sofia', 'Bekoratsaka'),
  ('Sofia', 'Malakialina'),
  ('Sofia', 'Betaramahamay'),
  ('Sofia', 'Komajia'),
  ('Sofia', 'Ampasimatera'),
  ('Sofia', 'Ambodihazoambo'),
  ('Betsiboka', 'Maevatanana I'),
  ('Betsiboka', 'Maevatanana II'),
  ('Betsiboka', 'Beratsimanina'),
  ('Betsiboka', 'Bemokotra'),
  ('Betsiboka', 'Mahazoma'),
  ('Betsiboka', 'Antsiafabositra'),
  ('Betsiboka', 'Antanimbary'),
  ('Betsiboka', 'Tsararano'),
  ('Betsiboka', 'Ambalajia'),
  ('Betsiboka', 'Ambalanjanakomby'),
  ('Betsiboka', 'Marokoro'),
  ('Betsiboka', 'Maria'),
  ('Betsiboka', 'Andriba'),
  ('Betsiboka', 'Mahatsinjo'),
  ('Betsiboka', 'Morafeno'),
  ('Betsiboka', 'Mangabe'),
  ('Betsiboka', 'Madiromirafy'),
  ('Betsiboka', 'Tsaratanana'),
  ('Betsiboka', 'Bekapaika'),
  ('Betsiboka', 'Tsararova'),
  ('Betsiboka', 'Betrandraka'),
  ('Betsiboka', 'Keliloha'),
  ('Betsiboka', 'Sarobaratra'),
  ('Betsiboka', 'Ampandrana'),
  ('Betsiboka', 'Andriamena'),
  ('Betsiboka', 'Ambakireny'),
  ('Betsiboka', 'Brieville'),
  ('Betsiboka', 'Sakoamadinika'),
  ('Betsiboka', 'Manakana'),
  ('Betsiboka', 'Kandreho'),
  ('Betsiboka', 'Ambaliha'),
  ('Betsiboka', 'Behazomaty'),
  ('Betsiboka', 'Antanimbaribe'),
  ('Betsiboka', 'Betaimboay'),
  ('Betsiboka', 'Andasibe'),
  ('Melaky', 'Soanenga'),
  ('Melaky', 'Bekodoka'),
  ('Melaky', 'Ambolodia Sud'),
  ('Melaky', 'Ankasakasa Tsibiray'),
  ('Melaky', 'Mahabe'),
  ('Melaky', 'Ambatomainty'),
  ('Melaky', 'Bemarivo'),
  ('Melaky', 'Sarodrano'),
  ('Melaky', 'Marotsialeha'),
  ('Melaky', 'Antsalova'),
  ('Melaky', 'Soahany'),
  ('Melaky', 'Masoarivo'),
  ('Melaky', 'Trangahy'),
  ('Melaky', 'Bekopaka'),
  ('Melaky', 'Maintirano'),
  ('Melaky', 'Mafaijijo'),
  ('Melaky', 'Andabotoka'),
  ('Melaky', 'Betanatanana'),
  ('Melaky', 'Andrea'),
  ('Melaky', 'Ankisatra'),
  ('Melaky', 'Marohazo'),
  ('Melaky', 'Antsondrodava'),
  ('Melaky', 'Belitsaky'),
  ('Melaky', 'Tambohorano'),
  ('Melaky', 'Veromanga'),
  ('Melaky', 'Maromavo'),
  ('Melaky', 'Andranovao'),
  ('Melaky', 'Antsaidoha Bebao'),
  ('Melaky', 'Berevo/ranobe'),
  ('Melaky', 'Bebaboky Sud'),
  ('Melaky', 'Bemokotra Sud'),
  ('Melaky', 'Morafenobe'),
  ('Melaky', 'Andramy'),
  ('Melaky', 'Beravina'),
  ('Atsimo Andrefana', 'Tanambao I'),
  ('Atsimo Andrefana', 'Tanambao II Tsf Nord'),
  ('Atsimo Andrefana', 'Mahavatse I'),
  ('Atsimo Andrefana', 'Mahavatse II'),
  ('Atsimo Andrefana', 'Betania'),
  ('Atsimo Andrefana', 'Besakoa'),
  ('Atsimo Andrefana', 'Beroroha'),
  ('Atsimo Andrefana', 'Bemavo'),
  ('Atsimo Andrefana', 'Fanjakana'),
  ('Atsimo Andrefana', 'Behisatsy'),
  ('Atsimo Andrefana', 'Marerano'),
  ('Atsimo Andrefana', 'Cu Morombe'),
  ('Atsimo Andrefana', 'Befandefa'),
  ('Atsimo Andrefana', 'Ambahikily'),
  ('Atsimo Andrefana', 'Antongo Vaovao'),
  ('Atsimo Andrefana', 'Nosy Ambositra'),
  ('Atsimo Andrefana', 'Befandriana Sud'),
  ('Atsimo Andrefana', 'Fotivolo'),
  ('Atsimo Andrefana', 'Tandrano'),
  ('Atsimo Andrefana', 'Andranomafana'),
  ('Atsimo Andrefana', 'Berenty'),
  ('Atsimo Andrefana', 'Ilemby'),
  ('Atsimo Andrefana', 'Betioky Atsimo'),
  ('Atsimo Andrefana', 'Sakamasay'),
  ('Atsimo Andrefana', 'Ambatry Mitsinjo'),
  ('Atsimo Andrefana', 'Ankazomanga Ouest'),
  ('Atsimo Andrefana', 'Maroarivo Ankazomanga'),
  ('Atsimo Andrefana', 'Beantake'),
  ('Atsimo Andrefana', 'Masiaboay'),
  ('Atsimo Andrefana', 'Antohabato'),
  ('Atsimo Andrefana', 'Tameantsoa'),
  ('Atsimo Andrefana', 'Tongobory'),
  ('Atsimo Andrefana', 'Besely'),
  ('Atsimo Andrefana', 'Vatolatsaka'),
  ('Atsimo Andrefana', 'Ankazombalala'),
  ('Atsimo Andrefana', 'Bezaha'),
  ('Atsimo Andrefana', 'Manalobe'),
  ('Atsimo Andrefana', 'Andranomangatsiaka'),
  ('Atsimo Andrefana', 'Ankiliabo'),
  ('Atsimo Andrefana', 'Amborompotsy'),
  ('Atsimo Andrefana', 'Ankilizato'),
  ('Atsimo Andrefana', 'Ankilivalo'),
  ('Atsimo Andrefana', 'Soamanonga'),
  ('Atsimo Andrefana', 'Fenoandala'),
  ('Atsimo Andrefana', 'Soaserana'),
  ('Atsimo Andrefana', 'Marosavoa'),
  ('Atsimo Andrefana', 'Salobe'),
  ('Atsimo Andrefana', 'Tanambao Haut'),
  ('Atsimo Andrefana', 'Belamoty'),
  ('Atsimo Andrefana', 'Antsavoa'),
  ('Atsimo Andrefana', 'Montifeno'),
  ('Atsimo Andrefana', 'Lazarivo'),
  ('Atsimo Andrefana', 'Ampanihy Ouest'),
  ('Atsimo Andrefana', 'Maniry'),
  ('Atsimo Andrefana', 'Antaly'),
  ('Atsimo Andrefana', 'Ankilimivory'),
  ('Atsimo Andrefana', 'Ejeda'),
  ('Atsimo Andrefana', 'Belafike Haut'),
  ('Atsimo Andrefana', 'Beahitse'),
  ('Atsimo Andrefana', 'Gogogogo'),
  ('Atsimo Andrefana', 'Androka'),
  ('Atsimo Andrefana', 'Vohitany'),
  ('Atsimo Andrefana', 'Beroy Atsimo'),
  ('Atsimo Andrefana', 'Fotadrevo'),
  ('Atsimo Andrefana', 'Itampolo'),
  ('Atsimo Andrefana', 'Sakaraha'),
  ('Atsimo Andrefana', 'Miary Taheza'),
  ('Atsimo Andrefana', 'Miary Lamatihy'),
  ('Atsimo Andrefana', 'Mahaboboka'),
  ('Atsimo Andrefana', 'Amboronabo'),
  ('Atsimo Andrefana', 'Bereketa'),
  ('Atsimo Andrefana', 'Andamasiny Vineta'),
  ('Atsimo Andrefana', 'Mihavatsy'),
  ('Atsimo Andrefana', 'Andranolava'),
  ('Atsimo Andrefana', 'Ambinany'),
  ('Atsimo Andrefana', 'Mikoboka'),
  ('Atsimo Andrefana', 'Mitsinjo'),
  ('Atsimo Andrefana', 'Mitsinjo Betanimena'),
  ('Atsimo Andrefana', 'Belalanda'),
  ('Atsimo Andrefana', 'Betsinjaka'),
  ('Atsimo Andrefana', 'Miary Ambohibola'),
  ('Atsimo Andrefana', 'Behompy'),
  ('Atsimo Andrefana', 'Maromiandra'),
  ('Atsimo Andrefana', 'Ambohimahavelona'),
  ('Atsimo Andrefana', 'Andranohinaly'),
  ('Atsimo Andrefana', 'Saint Augustin'),
  ('Atsimo Andrefana', 'Anakao'),
  ('Atsimo Andrefana', 'Soalara Sud'),
  ('Atsimo Andrefana', 'Ambolofoty'),
  ('Atsimo Andrefana', 'Ankilimalinike'),
  ('Atsimo Andrefana', 'Antanimena Onilahy'),
  ('Atsimo Andrefana', 'Manorofify'),
  ('Atsimo Andrefana', 'Marofoty'),
  ('Atsimo Andrefana', 'Tsianisiha'),
  ('Atsimo Andrefana', 'Manombo Sud'),
  ('Atsimo Andrefana', 'Andranovory'),
  ('Atsimo Andrefana', 'Milenaka'),
  ('Atsimo Andrefana', 'Ankililoaka'),
  ('Atsimo Andrefana', 'Analamisampy'),
  ('Atsimo Andrefana', 'Beheloka'),
  ('Atsimo Andrefana', 'Benenitra'),
  ('Atsimo Andrefana', 'Ianapera'),
  ('Atsimo Andrefana', 'Ambalavato'),
  ('Atsimo Andrefana', 'Ehara'),
  ('Androy', 'Beloha'),
  ('Androy', 'Tranovaho'),
  ('Androy', 'Kopoky'),
  ('Androy', 'Marolinta'),
  ('Androy', 'Tranoroa'),
  ('Androy', 'Behabobo'),
  ('Androy', 'Tsihombe'),
  ('Androy', 'Nikoly'),
  ('Androy', 'Betanty (Faux Cap)'),
  ('Androy', 'Anjampaly'),
  ('Androy', 'Marovato'),
  ('Androy', 'Antaritarika'),
  ('Androy', 'Imongy'),
  ('Androy', 'Ambovombe'),
  ('Androy', 'Tsimananada'),
  ('Androy', 'Erada'),
  ('Androy', 'Anjeky Ankilikira'),
  ('Androy', 'Ambanisarika'),
  ('Androy', 'Analamary'),
  ('Androy', 'Ambohimalaza'),
  ('Androy', 'Ambonaivo'),
  ('Androy', 'Maroalomainty'),
  ('Androy', 'Maroalopoty'),
  ('Androy', 'Ambondro'),
  ('Androy', 'Ambazoa'),
  ('Androy', 'Sihanamaro'),
  ('Androy', 'Marovato Befeno'),
  ('Androy', 'Antanimora Atsimo'),
  ('Androy', 'Andalatanosy'),
  ('Androy', 'Ampamata'),
  ('Androy', 'Jafaro'),
  ('Androy', 'Imanombo'),
  ('Androy', 'Morafeno Bekily'),
  ('Androy', 'Ankaranabo Nord'),
  ('Androy', 'Besakoa'),
  ('Androy', 'Anja Nord'),
  ('Androy', 'Antsakoamaro'),
  ('Androy', 'Ambatosola'),
  ('Androy', 'Tsirandrany'),
  ('Androy', 'Tsikolaky'),
  ('Androy', 'Manakompy'),
  ('Androy', 'Ambahita'),
  ('Androy', 'Maroviro'),
  ('Androy', 'Belindo Mahasoa'),
  ('Androy', 'Beteza'),
  ('Androy', 'Tanandava'),
  ('Androy', 'Bekitro'),
  ('Androy', 'Beraketa'),
  ('Androy', 'Vohimanga'),
  ('Androy', 'Bevitiky'),
  ('Androy', 'Anivorano Mitsinjo'),
  ('Anosy', 'Fort-Dauphin'),
  ('Anosy', 'Ampasy Nahampoana'),
  ('Anosy', 'Mandromondromotra'),
  ('Anosy', 'Soanierana'),
  ('Anosy', 'Ifarantsa'),
  ('Anosy', 'Isaka-Ivondro'),
  ('Anosy', 'Mandiso'),
  ('Anosy', 'Manambaro'),
  ('Anosy', 'Sarisambo'),
  ('Anosy', 'Ankaramena'),
  ('Anosy', 'Ranopiso'),
  ('Anosy', 'Ambatoabo'),
  ('Anosy', 'Ankariera'),
  ('Anosy', 'Analapatsy'),
  ('Anosy', 'Andranobory'),
  ('Anosy', 'Mahatalaky'),
  ('Anosy', 'Iaboakoho'),
  ('Anosy', 'Enaniliha'),
  ('Anosy', 'Fenoevo-Efita'),
  ('Anosy', 'Enakara-Haut'),
  ('Anosy', 'Ranomafana'),
  ('Anosy', 'Emagnobo'),
  ('Anosy', 'Bevoay'),
  ('Anosy', 'Ampasimena'),
  ('Anosy', 'Manantenina'),
  ('Anosy', 'Analamary (Taolagnaro)'),
  ('Anosy', 'Soavary'),
  ('Anosy', 'Betroka'),
  ('Anosy', 'Tsaraitso'),
  ('Anosy', 'Naninora'),
  ('Anosy', 'Ambalasoa'),
  ('Anosy', 'Ivahona'),
  ('Anosy', 'Analamary (Betroka)'),
  ('Anosy', 'Ianabinda'),
  ('Anosy', 'Benato Toby'),
  ('Anosy', 'Mahabo'),
  ('Anosy', 'Beampombo I'),
  ('Anosy', 'Jangany'),
  ('Anosy', 'Mahasoa Est'),
  ('Anosy', 'Bekorobo'),
  ('Anosy', 'Iaborotra'),
  ('Anosy', 'Isoanala'),
  ('Anosy', 'Beampombo II'),
  ('Anosy', 'Nanarena Besakoa'),
  ('Anosy', 'Ianakafy'),
  ('Anosy', 'Andriandampy'),
  ('Anosy', 'Sakamahily'),
  ('Anosy', 'Ambatomivary'),
  ('Anosy', 'Amboasary Atsimo'),
  ('Anosy', 'Behara'),
  ('Anosy', 'Tanandava Sud'),
  ('Anosy', 'Sampona'),
  ('Anosy', 'Ifotaka'),
  ('Anosy', 'Tranomaro'),
  ('Anosy', 'Maromby'),
  ('Anosy', 'Elonty'),
  ('Anosy', 'Esira'),
  ('Anosy', 'Mahaly'),
  ('Anosy', 'Manevy'),
  ('Anosy', 'Tsivory'),
  ('Anosy', 'Marotsiraka'),
  ('Anosy', 'Tomboarivo'),
  ('Anosy', 'Ebelo'),
  ('Anosy', 'Ranobe'),
  ('Menabe', 'Manja'),
  ('Menabe', 'Beharona'),
  ('Menabe', 'Anontsibe Centre'),
  ('Menabe', 'Soaserana'),
  ('Menabe', 'Ankiliabo'),
  ('Menabe', 'Andranopasy'),
  ('Menabe', 'Morondava'),
  ('Menabe', 'Bemanonga'),
  ('Menabe', 'Analaiva'),
  ('Menabe', 'Befasy'),
  ('Menabe', 'Belo Sur Mer'),
  ('Menabe', 'Mahabo'),
  ('Menabe', 'Ankilivalo'),
  ('Menabe', 'Analamitsivalana'),
  ('Menabe', 'Befotaka'),
  ('Menabe', 'Ampanihy (Mahabo)'),
  ('Menabe', 'Ankilizato'),
  ('Menabe', 'Ambia'),
  ('Menabe', 'Mandabe'),
  ('Menabe', 'Malaimbandy'),
  ('Menabe', 'Beronono'),
  ('Menabe', 'Mazavasoa'),
  ('Menabe', 'Belo Sur Tsiribihina'),
  ('Menabe', 'Andimaky Manambolo'),
  ('Menabe', 'Bemarivo Ankirondro'),
  ('Menabe', 'Tsimafana'),
  ('Menabe', 'Beroboka Nord'),
  ('Menabe', 'Tsaraotana'),
  ('Menabe', 'Masoarivo'),
  ('Menabe', 'Aboalimena'),
  ('Menabe', 'Ankalalobe'),
  ('Menabe', 'Ambiky'),
  ('Menabe', 'Berevo'),
  ('Menabe', 'Antsoha'),
  ('Menabe', 'Belinta'),
  ('Menabe', 'Ankiroroky'),
  ('Menabe', 'Miandrivazo'),
  ('Menabe', 'Dabolava'),
  ('Menabe', 'Bemahatazana'),
  ('Menabe', 'Ampanihy (Miandrivazo)'),
  ('Menabe', 'Anosimena'),
  ('Menabe', 'Manandaza'),
  ('Menabe', 'Ankotrofotsy'),
  ('Menabe', 'Isalo'),
  ('Menabe', 'Ambatolahy'),
  ('Menabe', 'Manambina'),
  ('Menabe', 'Itondy'),
  ('Menabe', 'Ankavandra'),
  ('Menabe', 'Soaloka'),
  ('Menabe', 'Betsipolitra'),
  ('Menabe', 'Ankondromena'),
  ('Diana', 'Ramena'),
  ('Diana', 'Sakaramy'),
  ('Diana', 'Antanamitarana'),
  ('Diana', 'Joffre Ville'),
  ('Diana', 'Antsahampano'),
  ('Diana', 'Mahavanona'),
  ('Diana', 'Mangaoka'),
  ('Diana', 'Andrafiabe'),
  ('Diana', 'Anketrakabe'),
  ('Diana', 'Sadjoavato'),
  ('Diana', 'Antsalaka'),
  ('Diana', 'Andranovondronina'),
  ('Diana', 'Andranofanjava'),
  ('Diana', 'Mahalina'),
  ('Diana', 'Ankarongana'),
  ('Diana', 'Anivorano Nord'),
  ('Diana', 'Antsoha'),
  ('Diana', 'Bobasakoa'),
  ('Diana', 'Ambondrona'),
  ('Diana', 'Bobakilandy'),
  ('Diana', 'Mosorolava'),
  ('Diana', 'Diego Suarez'),
  ('Diana', 'Ambilobe'),
  ('Diana', 'Mantaly'),
  ('Diana', 'Ampondralava'),
  ('Diana', 'Tanambao Marivorahona'),
  ('Diana', 'Ambakirano'),
  ('Diana', 'Ambatoben''anjavy'),
  ('Diana', 'Antsaravibe'),
  ('Diana', 'Antsohimbondrona'),
  ('Diana', 'Anjiabe Ambony'),
  ('Diana', 'Ambodibonara'),
  ('Diana', 'Beramanja'),
  ('Diana', 'Betsiaka'),
  ('Diana', 'Ambarakaraka'),
  ('Diana', 'Anaborano Ifasy'),
  ('Diana', 'Manambato'),
  ('Diana', 'Hell-Ville'),
  ('Diana', 'Ampangorina'),
  ('Diana', 'Ambatozavavy'),
  ('Diana', 'Bemanondrobe'),
  ('Diana', 'Dzamandzar'),
  ('Diana', 'Ambanja'),
  ('Diana', 'Benavony'),
  ('Diana', 'Ambohimena'),
  ('Diana', 'Antsatsaka'),
  ('Diana', 'Antranokarany'),
  ('Diana', 'Djangoa'),
  ('Diana', 'Antsakoamanondro'),
  ('Diana', 'Ambalahonko'),
  ('Diana', 'Ankingameloka'),
  ('Diana', 'Bemaneviky Haut Sambirano'),
  ('Diana', 'Ambodimanga Ramena'),
  ('Diana', 'Maevatanana'),
  ('Diana', 'Antafiambotry'),
  ('Diana', 'Maherivaratra'),
  ('Diana', 'Marovato'),
  ('Diana', 'Ambohitrandriana'),
  ('Diana', 'Ambohimarina'),
  ('Diana', 'Ambaliha'),
  ('Diana', 'Marotolana'),
  ('Diana', 'Bemaneviky Ouest'),
  ('Diana', 'Anorontsangana'),
  ('Diana', 'Antsirabe'),
  ('Diana', 'Ankatafa'),
  ('Sava', 'Antalaha Ambonivohitra'),
  ('Sava', 'Ampahana'),
  ('Sava', 'Ampohibe'),
  ('Sava', 'Antombana'),
  ('Sava', 'Antsahanoro'),
  ('Sava', 'Antananambo'),
  ('Sava', 'Marofinaritra'),
  ('Sava', 'Sarahandrano'),
  ('Sava', 'Andampy'),
  ('Sava', 'Ambalabe'),
  ('Sava', 'Ambinanifaho'),
  ('Sava', 'Ambohitralanana'),
  ('Sava', 'Lanjarivo'),
  ('Sava', 'Antsambalahy'),
  ('Sava', 'Vinanivao'),
  ('Sava', 'Ampanavoana'),
  ('Sava', 'Sambava Cu'),
  ('Sava', 'Ambohimalaza'),
  ('Sava', 'Farahalana'),
  ('Sava', 'Nosiarina'),
  ('Sava', 'Ambodivoara'),
  ('Sava', 'Anjinjaomby'),
  ('Sava', 'Morafeno'),
  ('Sava', 'Analamaho'),
  ('Sava', 'Ambohimitsinjo'),
  ('Sava', 'Anjangoveratra'),
  ('Sava', 'Andratamarina'),
  ('Sava', 'Marogaona'),
  ('Sava', 'Marojala'),
  ('Sava', 'Antsambaharo'),
  ('Sava', 'Andrahanjo'),
  ('Sava', 'Bemanevika'),
  ('Sava', 'Amboangibe'),
  ('Sava', 'Andrembona'),
  ('Sava', 'Antindra'),
  ('Sava', 'Ambodiampana'),
  ('Sava', 'Maroambihy'),
  ('Sava', 'Ambatoafo'),
  ('Sava', 'Anjialava'),
  ('Sava', 'Tanambao Daoud'),
  ('Sava', 'Antsahavaribe'),
  ('Sava', 'Bevonotra'),
  ('Sava', 'Andapa'),
  ('Sava', 'Tanandava'),
  ('Sava', 'Ankiakabe Nord'),
  ('Sava', 'Belaoka Marovato'),
  ('Sava', 'Ambodimanga I'),
  ('Sava', 'Marovato'),
  ('Sava', 'Andrakata'),
  ('Sava', 'Bealampona'),
  ('Sava', 'Matsohely'),
  ('Sava', 'Andranomena'),
  ('Sava', 'Ambalamanasy II'),
  ('Sava', 'Ambodiangezoka'),
  ('Sava', 'Betsakotsako Andranotsara'),
  ('Sava', 'Belaoka Lokoho'),
  ('Sava', 'Anoviara'),
  ('Sava', 'Doany'),
  ('Sava', 'Anjialavabe'),
  ('Sava', 'Antsahamena'),
  ('Sava', 'Vohemar'),
  ('Sava', 'Ampondra'),
  ('Sava', 'Fanambana'),
  ('Sava', 'Milanoa'),
  ('Sava', 'Bobakindro'),
  ('Sava', 'Daraina'),
  ('Sava', 'Ambalasatrana'),
  ('Sava', 'Tsarabaria'),
  ('Sava', 'Nosibe'),
  ('Sava', 'Andravory'),
  ('Sava', 'Andrafainkona'),
  ('Sava', 'Ampanefena'),
  ('Sava', 'Ambodisambalahy'),
  ('Sava', 'Ambinanin''andravory'),
  ('Sava', 'Amboriala'),
  ('Sava', 'Maromokotra Loky'),
  ('Sava', 'Antsirabe Nord'),
  ('Sava', 'Ampisikinana'),
  ('Sava', 'Belambo')
) AS x(region_nom,nom)
JOIN pays p ON p.nom='Madagascar'
JOIN region r ON r.id_pays=p.id AND r.nom=x.region_nom
ON CONFLICT (nom,id_region) DO NOTHING;

DO $$
DECLARE nr integer; nv integer;
BEGIN
  SELECT COUNT(*) INTO nr FROM region r JOIN pays p ON p.id=r.id_pays WHERE p.nom='Madagascar';
  SELECT COUNT(*) INTO nv FROM ville v JOIN region r ON r.id=v.id_region JOIN pays p ON p.id=r.id_pays WHERE p.nom='Madagascar';
  IF nr <> 24 THEN RAISE EXCEPTION 'Contrôle régions Madagascar: % au lieu de 24', nr; END IF;
  IF nv <> 1579 THEN RAISE EXCEPTION 'Contrôle communes importées: % au lieu de 1579', nv; END IF;
END $$;

COMMIT;

-- Contrôle final
SELECT COUNT(*) AS regions_madagascar FROM region r JOIN pays p ON p.id=r.id_pays WHERE p.nom='Madagascar';
SELECT COUNT(*) AS communes_madagascar FROM ville v JOIN region r ON r.id=v.id_region JOIN pays p ON p.id=r.id_pays WHERE p.nom='Madagascar';
